name: Build Electron app
on:
  push:
    branches:
      - master
    paths-ignore:
      - packages/web/**

jobs:
  build_on_win:
    runs-on: windows-latest

    concurrency:
      group: build-electron-dev-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-desktop-app-modules-v1
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile install
      - name: Build
        run: yarn app make
      - name: Upload the build
        uses: actions/upload-artifact@v2
        with:
          name: coh2-game-stats-dev-${{github.sha}}
          path: |
            packages/app/out/make/squirrel.windows/x64/*.exe
